version: '3.2'

services:
  postgres:
    image: postgres:12.3
    volumes:
       - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=google_crawler_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  phoenix:
    user: root
    build:
      context: "."
    ports:
      - "4000:4000"
    volumes:
      - .:/app

volumes:
    db_data:
